stages:
  - build
  - upload
  - release

cache:
  paths:
    - .*.o

build:
  stage: build
  image: ubuntu:18.04
  script:
    - export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
    - apt-get update && apt-get install --no-install-recommends -y
      build-essential
      automake
      cmake
      default-libmysqlclient-dev
      libboost-iostreams-dev
      libboost-system-dev
      libev-dev
      libjemalloc-dev
      libmysql++-dev
      default-libmysqlclient-dev
      mariadb-client
      pkg-config
      git
      libgoogle-glog-dev
    - ./configure CXXFLAGS=-D__DEBUG_BUILD__ --with-mysql-lib=/usr/lib/x86_64-linux-gnu/
      --with-ev-lib=/usr/lib/x86_64-linux-gnu/
      --with-boost-libdir=/usr/lib/x86_64-linux-gnu/
      --with-glog-lib=/usr/lib/x86_64-linux-gnu/
    - make && apt-get purge -y build-essential cmake pkg-config
    - apt-get autoremove -y && apt-get clean -y
    - rm -rf /var/lib/apt/lists/*
  artifacts:
    paths:
      - ocelot

variables:
  BINARY_NAME: "ocelot-${CI_COMMIT_TAG}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/ocelot/${CI_COMMIT_TAG}"

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ocelot "${PACKAGE_REGISTRY_URL}/${BINARY_NAME}"

release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${BINARY_NAME}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${BINARY_NAME}\"}"
