#!/usr/bin/env bash

# Wait for MySQL...
# ocelot.conf is generated by `cp ocelot.conf.dist ocelot.conf` and then customize it
CONF_FILE='./ocelot.conf'
get_conf_value_by_key() {
  grep "$1" ${CONF_FILE} | awk -F '=' '{print $2}' | xargs
}
MYSQL_HOST=$(get_conf_value_by_key mysql_host)
MYSQL_USER=$(get_conf_value_by_key mysql_username)
MYSQL_PASSWORD=$(get_conf_value_by_key mysql_password)

counter=1
while ! mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "show databases;" > /dev/null 2>&1; do
    sleep 1
    counter=$((counter + 1))
    if [ $((counter % 20)) -eq 0 ]; then
        mysql -h mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "show databases;"
        >&2 echo "Still waiting for MySQL (Count: $counter)."
    fi
done

./ocelot
